spring:
  jwt:
    secret-key: 5c127c4d752bfa53cb742f13dc00f86efa1ad4323e17c6fe82e5dfbf0ad4ef9ac2f3282a374f5bcd3406e5bcaac84500ac71e2c75c548d325f5b393036fb4b21
  oauth:
    naver:
      secret: _9dPawjBE4
      client-id: K0VS7pRNSWUDkGj14D91
      url:
        auth: https://nid.naver.com
        api: https://openapi.naver.com

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.orm.jdbc.bind: trace
